name: ephonefield
description: "Email and phone number auto detection"
version: 0.0.3
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # flags assets folder
  assets:
    - packages/ephonefield/assets/ad.png
    - packages/ephonefield/assets/ae.png
    - packages/ephonefield/assets/af.png
    - packages/ephonefield/assets/ag.png
    - packages/ephonefield/assets/ai.png
    - packages/ephonefield/assets/al.png
    - packages/ephonefield/assets/am.png
    - packages/ephonefield/assets/an.png
    - packages/ephonefield/assets/ao.png
    - packages/ephonefield/assets/aq.png
    - packages/ephonefield/assets/ar.png
    - packages/ephonefield/assets/as.png
    - packages/ephonefield/assets/at.png
    - packages/ephonefield/assets/au.png
    - packages/ephonefield/assets/aw.png
    - packages/ephonefield/assets/ax.png
    - packages/ephonefield/assets/az.png
    - packages/ephonefield/assets/ba.png
    - packages/ephonefield/assets/bb.png
    - packages/ephonefield/assets/bd.png
    - packages/ephonefield/assets/be.png
    - packages/ephonefield/assets/bf.png
    - packages/ephonefield/assets/bg.png
    - packages/ephonefield/assets/bh.png
    - packages/ephonefield/assets/bi.png
    - packages/ephonefield/assets/bj.png
    - packages/ephonefield/assets/bl.png
    - packages/ephonefield/assets/bm.png
    - packages/ephonefield/assets/bn.png
    - packages/ephonefield/assets/bo.png
    - packages/ephonefield/assets/bq.png
    - packages/ephonefield/assets/br.png
    - packages/ephonefield/assets/bs.png
    - packages/ephonefield/assets/bt.png
    - packages/ephonefield/assets/bv.png
    - packages/ephonefield/assets/bw.png
    - packages/ephonefield/assets/by.png
    - packages/ephonefield/assets/bz.png
    - packages/ephonefield/assets/ca.png
    - packages/ephonefield/assets/cc.png
    - packages/ephonefield/assets/cd.png
    - packages/ephonefield/assets/cf.png
    - packages/ephonefield/assets/cg.png
    - packages/ephonefield/assets/ch.png
    - packages/ephonefield/assets/ci.png
    - packages/ephonefield/assets/ck.png
    - packages/ephonefield/assets/cl.png
    - packages/ephonefield/assets/cm.png
    - packages/ephonefield/assets/cn.png
    - packages/ephonefield/assets/co.png
    - packages/ephonefield/assets/cr.png
    - packages/ephonefield/assets/cu.png
    - packages/ephonefield/assets/cv.png
    - packages/ephonefield/assets/cw.png
    - packages/ephonefield/assets/cx.png
    - packages/ephonefield/assets/cy.png
    - packages/ephonefield/assets/cz.png
    - packages/ephonefield/assets/de.png
    - packages/ephonefield/assets/dj.png
    - packages/ephonefield/assets/dk.png
    - packages/ephonefield/assets/dm.png
    - packages/ephonefield/assets/do.png
    - packages/ephonefield/assets/dz.png
    - packages/ephonefield/assets/ec.png
    - packages/ephonefield/assets/ee.png
    - packages/ephonefield/assets/eg.png
    - packages/ephonefield/assets/eh.png
    - packages/ephonefield/assets/er.png
    - packages/ephonefield/assets/es.png
    - packages/ephonefield/assets/et.png
    - packages/ephonefield/assets/eu.png
    - packages/ephonefield/assets/fi.png
    - packages/ephonefield/assets/fj.png
    - packages/ephonefield/assets/fk.png
    - packages/ephonefield/assets/fm.png
    - packages/ephonefield/assets/fo.png
    - packages/ephonefield/assets/fr.png
    - packages/ephonefield/assets/ga.png
    - packages/ephonefield/assets/gb.png
    - packages/ephonefield/assets/gb-eng.png
    - packages/ephonefield/assets/gb-nir.png
    - packages/ephonefield/assets/gb-sct.png
    - packages/ephonefield/assets/gb-wls.png
    - packages/ephonefield/assets/gd.png
    - packages/ephonefield/assets/ge.png
    - packages/ephonefield/assets/gf.png
    - packages/ephonefield/assets/gg.png
    - packages/ephonefield/assets/gh.png
    - packages/ephonefield/assets/gi.png
    - packages/ephonefield/assets/gl.png
    - packages/ephonefield/assets/gm.png
    - packages/ephonefield/assets/gn.png
    - packages/ephonefield/assets/gp.png
    - packages/ephonefield/assets/gq.png
    - packages/ephonefield/assets/gr.png
    - packages/ephonefield/assets/gs.png
    - packages/ephonefield/assets/gt.png
    - packages/ephonefield/assets/gu.png
    - packages/ephonefield/assets/gw.png
    - packages/ephonefield/assets/gy.png
    - packages/ephonefield/assets/hk.png
    - packages/ephonefield/assets/hm.png
    - packages/ephonefield/assets/hn.png
    - packages/ephonefield/assets/hr.png
    - packages/ephonefield/assets/ht.png
    - packages/ephonefield/assets/hu.png
    - packages/ephonefield/assets/id.png
    - packages/ephonefield/assets/ie.png
    - packages/ephonefield/assets/il.png
    - packages/ephonefield/assets/im.png
    - packages/ephonefield/assets/in.png
    - packages/ephonefield/assets/io.png
    - packages/ephonefield/assets/iq.png
    - packages/ephonefield/assets/ir.png
    - packages/ephonefield/assets/is.png
    - packages/ephonefield/assets/it.png
    - packages/ephonefield/assets/je.png
    - packages/ephonefield/assets/jm.png
    - packages/ephonefield/assets/jo.png
    - packages/ephonefield/assets/jp.png
    - packages/ephonefield/assets/ke.png
    - packages/ephonefield/assets/kg.png
    - packages/ephonefield/assets/kh.png
    - packages/ephonefield/assets/ki.png
    - packages/ephonefield/assets/km.png
    - packages/ephonefield/assets/kn.png
    - packages/ephonefield/assets/kp.png
    - packages/ephonefield/assets/kr.png
    - packages/ephonefield/assets/kw.png
    - packages/ephonefield/assets/ky.png
    - packages/ephonefield/assets/kz.png
    - packages/ephonefield/assets/la.png
    - packages/ephonefield/assets/lb.png
    - packages/ephonefield/assets/lc.png
    - packages/ephonefield/assets/li.png
    - packages/ephonefield/assets/lk.png
    - packages/ephonefield/assets/lr.png
    - packages/ephonefield/assets/ls.png
    - packages/ephonefield/assets/lt.png
    - packages/ephonefield/assets/lu.png
    - packages/ephonefield/assets/lv.png
    - packages/ephonefield/assets/ly.png
    - packages/ephonefield/assets/ma.png
    - packages/ephonefield/assets/mc.png
    - packages/ephonefield/assets/md.png
    - packages/ephonefield/assets/me.png
    - packages/ephonefield/assets/mf.png
    - packages/ephonefield/assets/mg.png
    - packages/ephonefield/assets/mh.png
    - packages/ephonefield/assets/mk.png
    - packages/ephonefield/assets/ml.png
    - packages/ephonefield/assets/mm.png
    - packages/ephonefield/assets/mn.png
    - packages/ephonefield/assets/mo.png
    - packages/ephonefield/assets/mp.png
    - packages/ephonefield/assets/mq.png
    - packages/ephonefield/assets/mr.png
    - packages/ephonefield/assets/ms.png
    - packages/ephonefield/assets/mt.png
    - packages/ephonefield/assets/mu.png
    - packages/ephonefield/assets/mv.png
    - packages/ephonefield/assets/mw.png
    - packages/ephonefield/assets/mx.png
    - packages/ephonefield/assets/my.png
    - packages/ephonefield/assets/mz.png
    - packages/ephonefield/assets/na.png
    - packages/ephonefield/assets/nc.png
    - packages/ephonefield/assets/ne.png
    - packages/ephonefield/assets/nf.png
    - packages/ephonefield/assets/ng.png
    - packages/ephonefield/assets/ni.png
    - packages/ephonefield/assets/nl.png
    - packages/ephonefield/assets/no.png
    - packages/ephonefield/assets/np.png
    - packages/ephonefield/assets/nr.png
    - packages/ephonefield/assets/nu.png
    - packages/ephonefield/assets/nz.png
    - packages/ephonefield/assets/om.png
    - packages/ephonefield/assets/pa.png
    - packages/ephonefield/assets/pe.png
    - packages/ephonefield/assets/pf.png
    - packages/ephonefield/assets/pg.png
    - packages/ephonefield/assets/ph.png
    - packages/ephonefield/assets/pk.png
    - packages/ephonefield/assets/pl.png
    - packages/ephonefield/assets/pm.png
    - packages/ephonefield/assets/pn.png
    - packages/ephonefield/assets/pr.png
    - packages/ephonefield/assets/ps.png
    - packages/ephonefield/assets/pt.png
    - packages/ephonefield/assets/pw.png
    - packages/ephonefield/assets/py.png
    - packages/ephonefield/assets/qa.png
    - packages/ephonefield/assets/re.png
    - packages/ephonefield/assets/ro.png
    - packages/ephonefield/assets/rs.png
    - packages/ephonefield/assets/ru.png
    - packages/ephonefield/assets/rw.png
    - packages/ephonefield/assets/sa.png
    - packages/ephonefield/assets/sb.png
    - packages/ephonefield/assets/sc.png
    - packages/ephonefield/assets/sd.png
    - packages/ephonefield/assets/se.png
    - packages/ephonefield/assets/sg.png
    - packages/ephonefield/assets/sh.png
    - packages/ephonefield/assets/si.png
    - packages/ephonefield/assets/sj.png
    - packages/ephonefield/assets/sk.png
    - packages/ephonefield/assets/sl.png
    - packages/ephonefield/assets/sm.png
    - packages/ephonefield/assets/sn.png
    - packages/ephonefield/assets/so.png
    - packages/ephonefield/assets/sr.png
    - packages/ephonefield/assets/ss.png
    - packages/ephonefield/assets/st.png
    - packages/ephonefield/assets/sv.png
    - packages/ephonefield/assets/sx.png
    - packages/ephonefield/assets/sy.png
    - packages/ephonefield/assets/sz.png
    - packages/ephonefield/assets/tc.png
    - packages/ephonefield/assets/td.png
    - packages/ephonefield/assets/tf.png
    - packages/ephonefield/assets/tg.png
    - packages/ephonefield/assets/th.png
    - packages/ephonefield/assets/tj.png
    - packages/ephonefield/assets/tk.png
    - packages/ephonefield/assets/tl.png
    - packages/ephonefield/assets/tm.png
    - packages/ephonefield/assets/tn.png
    - packages/ephonefield/assets/to.png
    - packages/ephonefield/assets/tr.png
    - packages/ephonefield/assets/tt.png
    - packages/ephonefield/assets/tv.png
    - packages/ephonefield/assets/tw.png
    - packages/ephonefield/assets/tz.png
    - packages/ephonefield/assets/ua.png
    - packages/ephonefield/assets/ug.png
    - packages/ephonefield/assets/um.png
    - packages/ephonefield/assets/us.png
    - packages/ephonefield/assets/uy.png
    - packages/ephonefield/assets/uz.png
    - packages/ephonefield/assets/va.png
    - packages/ephonefield/assets/vc.png
    - packages/ephonefield/assets/ve.png
    - packages/ephonefield/assets/vg.png
    - packages/ephonefield/assets/vi.png
    - packages/ephonefield/assets/vn.png
    - packages/ephonefield/assets/vu.png
    - packages/ephonefield/assets/wf.png
    - packages/ephonefield/assets/ws.png
    - packages/ephonefield/assets/xk.png
    - packages/ephonefield/assets/ye.png
    - packages/ephonefield/assets/yt.png
    - packages/ephonefield/assets/za.png
    - packages/ephonefield/assets/zm.png
    - packages/ephonefield/assets/zw.png
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
