name: ephonefield
description: "Email and phone number auto detection"
version: 0.0.2
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # flags assets folder
  assets:
    - packages/ephonefield/flags/ad.png
    - packages/ephonefield/flags/ae.png
    - packages/ephonefield/flags/af.png
    - packages/ephonefield/flags/ag.png
    - packages/ephonefield/flags/ai.png
    - packages/ephonefield/flags/al.png
    - packages/ephonefield/flags/am.png
    - packages/ephonefield/flags/an.png
    - packages/ephonefield/flags/ao.png
    - packages/ephonefield/flags/aq.png
    - packages/ephonefield/flags/ar.png
    - packages/ephonefield/flags/as.png
    - packages/ephonefield/flags/at.png
    - packages/ephonefield/flags/au.png
    - packages/ephonefield/flags/aw.png
    - packages/ephonefield/flags/ax.png
    - packages/ephonefield/flags/az.png
    - packages/ephonefield/flags/ba.png
    - packages/ephonefield/flags/bb.png
    - packages/ephonefield/flags/bd.png
    - packages/ephonefield/flags/be.png
    - packages/ephonefield/flags/bf.png
    - packages/ephonefield/flags/bg.png
    - packages/ephonefield/flags/bh.png
    - packages/ephonefield/flags/bi.png
    - packages/ephonefield/flags/bj.png
    - packages/ephonefield/flags/bl.png
    - packages/ephonefield/flags/bm.png
    - packages/ephonefield/flags/bn.png
    - packages/ephonefield/flags/bo.png
    - packages/ephonefield/flags/bq.png
    - packages/ephonefield/flags/br.png
    - packages/ephonefield/flags/bs.png
    - packages/ephonefield/flags/bt.png
    - packages/ephonefield/flags/bv.png
    - packages/ephonefield/flags/bw.png
    - packages/ephonefield/flags/by.png
    - packages/ephonefield/flags/bz.png
    - packages/ephonefield/flags/ca.png
    - packages/ephonefield/flags/cc.png
    - packages/ephonefield/flags/cd.png
    - packages/ephonefield/flags/cf.png
    - packages/ephonefield/flags/cg.png
    - packages/ephonefield/flags/ch.png
    - packages/ephonefield/flags/ci.png
    - packages/ephonefield/flags/ck.png
    - packages/ephonefield/flags/cl.png
    - packages/ephonefield/flags/cm.png
    - packages/ephonefield/flags/cn.png
    - packages/ephonefield/flags/co.png
    - packages/ephonefield/flags/cr.png
    - packages/ephonefield/flags/cu.png
    - packages/ephonefield/flags/cv.png
    - packages/ephonefield/flags/cw.png
    - packages/ephonefield/flags/cx.png
    - packages/ephonefield/flags/cy.png
    - packages/ephonefield/flags/cz.png
    - packages/ephonefield/flags/de.png
    - packages/ephonefield/flags/dj.png
    - packages/ephonefield/flags/dk.png
    - packages/ephonefield/flags/dm.png
    - packages/ephonefield/flags/do.png
    - packages/ephonefield/flags/dz.png
    - packages/ephonefield/flags/ec.png
    - packages/ephonefield/flags/ee.png
    - packages/ephonefield/flags/eg.png
    - packages/ephonefield/flags/eh.png
    - packages/ephonefield/flags/er.png
    - packages/ephonefield/flags/es.png
    - packages/ephonefield/flags/et.png
    - packages/ephonefield/flags/eu.png
    - packages/ephonefield/flags/fi.png
    - packages/ephonefield/flags/fj.png
    - packages/ephonefield/flags/fk.png
    - packages/ephonefield/flags/fm.png
    - packages/ephonefield/flags/fo.png
    - packages/ephonefield/flags/fr.png
    - packages/ephonefield/flags/ga.png
    - packages/ephonefield/flags/gb.png
    - packages/ephonefield/flags/gb-eng.png
    - packages/ephonefield/flags/gb-nir.png
    - packages/ephonefield/flags/gb-sct.png
    - packages/ephonefield/flags/gb-wls.png
    - packages/ephonefield/flags/gd.png
    - packages/ephonefield/flags/ge.png
    - packages/ephonefield/flags/gf.png
    - packages/ephonefield/flags/gg.png
    - packages/ephonefield/flags/gh.png
    - packages/ephonefield/flags/gi.png
    - packages/ephonefield/flags/gl.png
    - packages/ephonefield/flags/gm.png
    - packages/ephonefield/flags/gn.png
    - packages/ephonefield/flags/gp.png
    - packages/ephonefield/flags/gq.png
    - packages/ephonefield/flags/gr.png
    - packages/ephonefield/flags/gs.png
    - packages/ephonefield/flags/gt.png
    - packages/ephonefield/flags/gu.png
    - packages/ephonefield/flags/gw.png
    - packages/ephonefield/flags/gy.png
    - packages/ephonefield/flags/hk.png
    - packages/ephonefield/flags/hm.png
    - packages/ephonefield/flags/hn.png
    - packages/ephonefield/flags/hr.png
    - packages/ephonefield/flags/ht.png
    - packages/ephonefield/flags/hu.png
    - packages/ephonefield/flags/id.png
    - packages/ephonefield/flags/ie.png
    - packages/ephonefield/flags/il.png
    - packages/ephonefield/flags/im.png
    - packages/ephonefield/flags/in.png
    - packages/ephonefield/flags/io.png
    - packages/ephonefield/flags/iq.png
    - packages/ephonefield/flags/ir.png
    - packages/ephonefield/flags/is.png
    - packages/ephonefield/flags/it.png
    - packages/ephonefield/flags/je.png
    - packages/ephonefield/flags/jm.png
    - packages/ephonefield/flags/jo.png
    - packages/ephonefield/flags/jp.png
    - packages/ephonefield/flags/ke.png
    - packages/ephonefield/flags/kg.png
    - packages/ephonefield/flags/kh.png
    - packages/ephonefield/flags/ki.png
    - packages/ephonefield/flags/km.png
    - packages/ephonefield/flags/kn.png
    - packages/ephonefield/flags/kp.png
    - packages/ephonefield/flags/kr.png
    - packages/ephonefield/flags/kw.png
    - packages/ephonefield/flags/ky.png
    - packages/ephonefield/flags/kz.png
    - packages/ephonefield/flags/la.png
    - packages/ephonefield/flags/lb.png
    - packages/ephonefield/flags/lc.png
    - packages/ephonefield/flags/li.png
    - packages/ephonefield/flags/lk.png
    - packages/ephonefield/flags/lr.png
    - packages/ephonefield/flags/ls.png
    - packages/ephonefield/flags/lt.png
    - packages/ephonefield/flags/lu.png
    - packages/ephonefield/flags/lv.png
    - packages/ephonefield/flags/ly.png
    - packages/ephonefield/flags/ma.png
    - packages/ephonefield/flags/mc.png
    - packages/ephonefield/flags/md.png
    - packages/ephonefield/flags/me.png
    - packages/ephonefield/flags/mf.png
    - packages/ephonefield/flags/mg.png
    - packages/ephonefield/flags/mh.png
    - packages/ephonefield/flags/mk.png
    - packages/ephonefield/flags/ml.png
    - packages/ephonefield/flags/mm.png
    - packages/ephonefield/flags/mn.png
    - packages/ephonefield/flags/mo.png
    - packages/ephonefield/flags/mp.png
    - packages/ephonefield/flags/mq.png
    - packages/ephonefield/flags/mr.png
    - packages/ephonefield/flags/ms.png
    - packages/ephonefield/flags/mt.png
    - packages/ephonefield/flags/mu.png
    - packages/ephonefield/flags/mv.png
    - packages/ephonefield/flags/mw.png
    - packages/ephonefield/flags/mx.png
    - packages/ephonefield/flags/my.png
    - packages/ephonefield/flags/mz.png
    - packages/ephonefield/flags/na.png
    - packages/ephonefield/flags/nc.png
    - packages/ephonefield/flags/ne.png
    - packages/ephonefield/flags/nf.png
    - packages/ephonefield/flags/ng.png
    - packages/ephonefield/flags/ni.png
    - packages/ephonefield/flags/nl.png
    - packages/ephonefield/flags/no.png
    - packages/ephonefield/flags/np.png
    - packages/ephonefield/flags/nr.png
    - packages/ephonefield/flags/nu.png
    - packages/ephonefield/flags/nz.png
    - packages/ephonefield/flags/om.png
    - packages/ephonefield/flags/pa.png
    - packages/ephonefield/flags/pe.png
    - packages/ephonefield/flags/pf.png
    - packages/ephonefield/flags/pg.png
    - packages/ephonefield/flags/ph.png
    - packages/ephonefield/flags/pk.png
    - packages/ephonefield/flags/pl.png
    - packages/ephonefield/flags/pm.png
    - packages/ephonefield/flags/pn.png
    - packages/ephonefield/flags/pr.png
    - packages/ephonefield/flags/ps.png
    - packages/ephonefield/flags/pt.png
    - packages/ephonefield/flags/pw.png
    - packages/ephonefield/flags/py.png
    - packages/ephonefield/flags/qa.png
    - packages/ephonefield/flags/re.png
    - packages/ephonefield/flags/ro.png
    - packages/ephonefield/flags/rs.png
    - packages/ephonefield/flags/ru.png
    - packages/ephonefield/flags/rw.png
    - packages/ephonefield/flags/sa.png
    - packages/ephonefield/flags/sb.png
    - packages/ephonefield/flags/sc.png
    - packages/ephonefield/flags/sd.png
    - packages/ephonefield/flags/se.png
    - packages/ephonefield/flags/sg.png
    - packages/ephonefield/flags/sh.png
    - packages/ephonefield/flags/si.png
    - packages/ephonefield/flags/sj.png
    - packages/ephonefield/flags/sk.png
    - packages/ephonefield/flags/sl.png
    - packages/ephonefield/flags/sm.png
    - packages/ephonefield/flags/sn.png
    - packages/ephonefield/flags/so.png
    - packages/ephonefield/flags/sr.png
    - packages/ephonefield/flags/ss.png
    - packages/ephonefield/flags/st.png
    - packages/ephonefield/flags/sv.png
    - packages/ephonefield/flags/sx.png
    - packages/ephonefield/flags/sy.png
    - packages/ephonefield/flags/sz.png
    - packages/ephonefield/flags/tc.png
    - packages/ephonefield/flags/td.png
    - packages/ephonefield/flags/tf.png
    - packages/ephonefield/flags/tg.png
    - packages/ephonefield/flags/th.png
    - packages/ephonefield/flags/tj.png
    - packages/ephonefield/flags/tk.png
    - packages/ephonefield/flags/tl.png
    - packages/ephonefield/flags/tm.png
    - packages/ephonefield/flags/tn.png
    - packages/ephonefield/flags/to.png
    - packages/ephonefield/flags/tr.png
    - packages/ephonefield/flags/tt.png
    - packages/ephonefield/flags/tv.png
    - packages/ephonefield/flags/tw.png
    - packages/ephonefield/flags/tz.png
    - packages/ephonefield/flags/ua.png
    - packages/ephonefield/flags/ug.png
    - packages/ephonefield/flags/um.png
    - packages/ephonefield/flags/us.png
    - packages/ephonefield/flags/uy.png
    - packages/ephonefield/flags/uz.png
    - packages/ephonefield/flags/va.png
    - packages/ephonefield/flags/vc.png
    - packages/ephonefield/flags/ve.png
    - packages/ephonefield/flags/vg.png
    - packages/ephonefield/flags/vi.png
    - packages/ephonefield/flags/vn.png
    - packages/ephonefield/flags/vu.png
    - packages/ephonefield/flags/wf.png
    - packages/ephonefield/flags/ws.png
    - packages/ephonefield/flags/xk.png
    - packages/ephonefield/flags/ye.png
    - packages/ephonefield/flags/yt.png
    - packages/ephonefield/flags/za.png
    - packages/ephonefield/flags/zm.png
    - packages/ephonefield/flags/zw.png
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
